feat: check for trailing slash

diff --git a/scripts/k8s-prepare b/scripts/k8s-prepare
--- a/scripts/k8s-prepare
+++ b/scripts/k8s-prepare
@@ -34,23 +34,45 @@ DEST_DIR=$2
 DEST_DIR=${DEST_DIR:-"./deployment/"}
 EXTENSION="yml"
 
+# check for trailing slashes
+case "$SOURCE_DIR" in
+*/)
+    ;;
+*)
+    SOURCE_DIR="$SOURCE_DIR/"
+    ;;
+esac
+
+case "$DEST_DIR" in
+*/)
+    ;;
+*)
+    DEST_DIR="$DEST_DIR/"
+    ;;
+esac
+
+if [ ! -d $SOURCE_DIR ]; then
+  echo "Source directory does not exist. Aborting."
+  exit 1
+fi
+
 echo "Moving *.$EXTENSION from $SOURCE_DIR to $DEST_DIR"
 
 if [ -d $DEST_DIR ]; then
-  echo "Destination directory already exists, deleting content."
+  echo "Destination directory already exists, deleting directory."
   rm -rf $DEST_DIR
 fi
 
 echo "Creating destination directory"
-mkdir $DEST_DIR
+mkdir -p $DEST_DIR
 
 for file in $(find $SOURCE_DIR -regex ".*\.$EXTENSION$")
 do
   name=${file#$SOURCE_DIR}
   name=${name//\//-}
-  destFile=$DEST_DIR/$name
-
-  echo "Copying $file to $destFile and replace env vars"
+  name=${name#-}
+  destFile=$DEST_DIR$name
+  echo "Copying $name to $destFile and replace env vars"
 
   envsubst < "$file" > "$destFile"
 done
